<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\SmartEC3\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\SmartEC3\Entity\SmartRegiImage;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * SmartRegiImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmartRegiImageRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, SmartRegiImage::class);
    }
}
